// SPDX-License-Identifier: Apache-2.0
//! Reader for the SDK's committed error catalog
//! (`<sdk>/metadata/error-catalog.json`) — the machine-readable index behind
//! the `docs/diagnostics/ALP-B*.md` runtime diagnostics and the `ALP_ERR_*`
//! enum in `include/alp/peripheral.h` (auto-generated by the SDK's
//! `scripts/gen_error_catalog.py`). This module only parses the already-read
//! JSON text — pure, no filesystem access — so it stays consistent with the
//! rest of `alp-core`; the CLI does the actual read (see
//! `alp-cli/src/commands/explain.rs`).

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// One entry in the catalog: a single `ALP-Bxxx` runtime diagnostic or
/// `ALP_ERR_*` API error code.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ErrorCatalogEntry {
    /// The code itself (also the map key it's stored under).
    pub code: String,
    /// Where the code is documented: a `docs/diagnostics/*.md` path for
    /// `ALP-B*`, or the defining header (e.g. `include/alp/peripheral.h`) for
    /// `ALP_ERR_*`.
    pub doc: String,
    /// Category: `"runtime-diagnostic"` (`ALP-B*`) or `"api-error"` (`ALP_ERR_*`).
    pub kind: String,
    /// One-line description.
    pub summary: String,
    /// Why the condition occurs, when the catalog has one — the SDK's own
    /// `alp explain` renders `summary / cause / fix / doc` in that order
    /// (`alp-sdk-upstream/scripts/alp_cli/explain.py`); this CLI previously
    /// parsed the catalog without a field for it, so a populated `cause`
    /// silently vanished.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cause: Option<String>,
    /// Suggested remediation, when the catalog has one (not every entry does).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fix: Option<String>,
}

/// On-disk shape of `metadata/error-catalog.json`: a `_banner` (ignored — it's
/// just the "auto-generated, don't edit" notice) plus the `code -> entry` map.
#[derive(Debug, Deserialize)]
struct ErrorCatalogFile {
    codes: BTreeMap<String, ErrorCatalogEntry>,
}

/// Why a catalog document could not be parsed.
#[derive(Debug, thiserror::Error)]
pub enum ErrorCatalogError {
    /// The document failed JSON deserialization; holds the parse error text.
    #[error("error catalog is not valid JSON: {0}")]
    Json(String),
}

/// The parsed catalog: every code, keyed by its literal string (e.g.
/// `ALP-B005`, `ALP_ERR_TIMEOUT`).
pub type ErrorCatalog = BTreeMap<String, ErrorCatalogEntry>;

/// Parse `metadata/error-catalog.json`'s text into a `code -> entry` map. Pure
/// — no IO; the caller reads the file (see `load_error_catalog` in the CLI's
/// `explain` command for the filesystem-backed wrapper convention used
/// elsewhere in this crate, e.g. `parse_build_plan`).
pub fn parse_error_catalog(json: &str) -> Result<ErrorCatalog, ErrorCatalogError> {
    let file: ErrorCatalogFile =
        serde_json::from_str(json).map_err(|e| ErrorCatalogError::Json(e.to_string()))?;
    Ok(file.codes)
}

/// Look up a single code, case-insensitively — mirrors the SDK's own `alp
/// explain`, which normalises the query with `.strip().upper()` before
/// matching (`alp-sdk-upstream/scripts/alp_cli/explain.py::_normalise`), so
/// `alp explain alp-b014` matches the catalog's canonical `ALP-B014` key.
/// Catalog keys are always that canonical uppercase form (`ALP-Bxxx` /
/// `ALP_ERR_*`), so upper-casing the query alone is enough — no per-entry
/// case folding needed. Still no fuzzy matching (no typo suggestions).
pub fn find_error_code<'a>(catalog: &'a ErrorCatalog, code: &str) -> Option<&'a ErrorCatalogEntry> {
    catalog.get(&code.to_uppercase())
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"{
      "_banner": "AUTO-GENERATED -- DO NOT EDIT",
      "codes": {
        "ALP-B007": {
          "code": "ALP-B007",
          "doc": "docs/diagnostics/ALP-B007.md",
          "fix": "Use a board preset that hosts the SoM family, or define a compatible custom board inline in `board.yaml`.",
          "kind": "runtime-diagnostic",
          "summary": "The selected board preset does not list the selected SoM preset's `family:` in `hosts_som_families:`."
        },
        "ALP_ERR_TIMEOUT": {
          "code": "ALP_ERR_TIMEOUT",
          "doc": "include/alp/peripheral.h",
          "kind": "api-error",
          "summary": "Operation timed out."
        }
      }
    }"#;

    #[test]
    fn parses_entries_with_and_without_fix() {
        let catalog = parse_error_catalog(SAMPLE).unwrap();
        assert_eq!(catalog.len(), 2);

        let b007 = find_error_code(&catalog, "ALP-B007").unwrap();
        assert_eq!(b007.kind, "runtime-diagnostic");
        assert!(b007.fix.is_some());

        let timeout = find_error_code(&catalog, "ALP_ERR_TIMEOUT").unwrap();
        assert_eq!(timeout.kind, "api-error");
        assert!(timeout.fix.is_none());
    }

    #[test]
    fn unknown_code_is_none() {
        let catalog = parse_error_catalog(SAMPLE).unwrap();
        assert!(find_error_code(&catalog, "ALP-B999").is_none());
    }

    #[test]
    fn lookup_is_case_insensitive() {
        // F7: mirrors the SDK's own `alp explain`, which is case-insensitive.
        let catalog = parse_error_catalog(SAMPLE).unwrap();
        let lower = find_error_code(&catalog, "alp-b007").unwrap();
        assert_eq!(lower.code, "ALP-B007");
        let mixed = find_error_code(&catalog, "Alp_Err_Timeout").unwrap();
        assert_eq!(mixed.code, "ALP_ERR_TIMEOUT");
    }

    #[test]
    fn cause_is_none_when_absent_and_parses_when_present() {
        let catalog = parse_error_catalog(SAMPLE).unwrap();
        let b007 = find_error_code(&catalog, "ALP-B007").unwrap();
        assert!(b007.cause.is_none());

        let with_cause = r#"{
          "codes": {
            "ALP-B900": {
              "code": "ALP-B900",
              "doc": "docs/diagnostics/ALP-B900.md",
              "kind": "runtime-diagnostic",
              "summary": "s",
              "cause": "the board preset doesn't declare this peripheral"
            }
          }
        }"#;
        let catalog = parse_error_catalog(with_cause).unwrap();
        let entry = find_error_code(&catalog, "ALP-B900").unwrap();
        assert_eq!(
            entry.cause.as_deref(),
            Some("the board preset doesn't declare this peripheral")
        );
    }

    #[test]
    fn malformed_json_errors() {
        let err = parse_error_catalog("not json").unwrap_err();
        assert!(matches!(err, ErrorCatalogError::Json(_)));
    }
}
