// SPDX-License-Identifier: Apache-2.0
//! **PROOF BENCH** (branch `proof/pmt-aen701`). Reproduce the SDK's
//! `alp_orchestrate.py --emit build-plan` for **E1M-AEN701** from
//! **policy / metadata / template DATA alone**, parity-gated byte-for-byte
//! against the real SDK emit captured under `spike_fixtures/oracle/`.
//!
//! The thesis (issue alplabai/alp-sdk#235): per-silicon build knowledge is data,
//! not hardcoded Python. Each stage proves one more artefact derives from data:
//!   * **Stage A (this commit)** — the `a32_cluster` Yocto slice's `local.conf`,
//!     byte-identical, from `board.yaml` (cores) + the SoM topology (machine).
//!
//! Layers, kept explicit:
//!   * METADATA — `board.yaml` + the SoM preset (`E1M-AEN701.yaml`) topology.
//!   * POLICY   — the derivation rules (lib→recipe transform, machine fallback,
//!     backend selection). Inline here; externalised to `policy.json` in a later
//!     stage (registries_spike / policy_engine_spike already prove the shape).
//!   * TEMPLATE — the `local.conf` line shapes the engine fills.
//!   * ENGINE   — resolve(board+topology) → render(template) → a build-plan slice.

use std::collections::BTreeMap;

use serde::Deserialize;

use crate::build_plan::{Backend, BuildSlice, GeneratedFile, ToolStep};

// ===========================================================================
// METADATA — board.yaml (the consumer's project file)
// ===========================================================================

#[derive(Debug, Clone, Deserialize)]
struct BoardYaml {
    som: BoardSom,
    #[serde(default)]
    cores: BTreeMap<String, BoardCore>,
}

#[derive(Debug, Clone, Deserialize)]
struct BoardSom {
    sku: String,
}

#[derive(Debug, Clone, Deserialize, Default)]
struct BoardCore {
    #[serde(default)]
    image: Option<String>,
    #[serde(default)]
    libraries: Vec<String>,
}

// ===========================================================================
// METADATA — the SoM preset topology (per-core machine/board/toolchain)
// ===========================================================================

#[derive(Debug, Clone, Deserialize)]
struct SomPreset {
    #[allow(dead_code)]
    sku: String,
    #[serde(default)]
    topology: BTreeMap<String, TopoCore>,
}

#[derive(Debug, Clone, Deserialize)]
struct TopoCore {
    /// Yocto MACHINE (present ⇒ this core builds under Yocto).
    #[serde(default)]
    machine: Option<String>,
    /// Zephyr board target (present ⇒ this core builds under Zephyr).
    #[serde(default)]
    board: Option<String>,
}

// ===========================================================================
// POLICY — the per-silicon rules (inline now; externalised to policy.json later)
// ===========================================================================

/// A Yocto library name → its bitbake recipe: `lib-<name with _→->`.
/// (alp_orchestrate.py:3294 — `f"lib-{lib.replace('_', '-')}"`.)
fn lib_to_recipe(lib: &str) -> String {
    format!("lib-{}", lib.replace('_', "-"))
}

/// MACHINE: the SoM topology value, else the fallback `e1m-<sku sans e1m->`.
/// (alp_orchestrate.py:3285 — `slice_.machine or f"e1m-{sku.lower().replace('e1m-','')}"`.)
fn yocto_machine(topo_machine: Option<&str>, sku: &str) -> String {
    match topo_machine {
        Some(m) => m.to_string(),
        None => format!("e1m-{}", sku.to_lowercase().replace("e1m-", "")),
    }
}

// ===========================================================================
// TEMPLATE + ENGINE — render the Yocto local.conf from resolved facts
// ===========================================================================

/// The resolved facts for one Yocto slice (metadata after board⊕topology merge).
struct YoctoSlice {
    core_id: String,
    image: String,
    machine: String,
    libraries: Vec<String>,
}

/// Resolve a Yocto core: board.yaml supplies image + libraries; the SoM topology
/// supplies the MACHINE. Returns `None` if the core isn't a Yocto core.
fn resolve_yocto_slice(board: &BoardYaml, som: &SomPreset, core_id: &str) -> Option<YoctoSlice> {
    let topo = som.topology.get(core_id)?;
    // Backend selection (POLICY): a `machine` in the topology ⇒ Yocto.
    if topo.machine.is_none() || topo.board.is_some() {
        return None;
    }
    let core = board.cores.get(core_id)?;
    Some(YoctoSlice {
        core_id: core_id.to_string(),
        image: core.image.clone()?,
        machine: yocto_machine(topo.machine.as_deref(), &board.som.sku),
        libraries: core.libraries.clone(),
    })
}

/// Render the slice's `build/<core>-yocto/local.conf` — the exact shape
/// alp_orchestrate.py emits (header → MACHINE → IMAGE_INSTALL? → bitbake target).
fn render_yocto_local_conf(s: &YoctoSlice) -> String {
    let mut lines = vec![
        "# Auto-generated by scripts/alp_orchestrate.py -- append to local.conf.".to_string(),
        format!("# Per-core slice `{}` (image: {})", s.core_id, s.image),
        format!("MACHINE = \"{}\"", s.machine),
    ];
    if !s.libraries.is_empty() {
        let recipes: Vec<String> = s.libraries.iter().map(|l| lib_to_recipe(l)).collect();
        lines.push(format!("IMAGE_INSTALL:append = \" {}\"", recipes.join(" ")));
    }
    lines.push(format!("# bitbake target: {}", s.image));
    format!("{}\n", lines.join("\n"))
}

/// Assemble the full build-plan slice for a Yocto core — the shipped `BuildSlice`
/// the SDK's consumer accepts (`build/<core>-yocto/`, a `bitbake <image>` step).
/// `sdk_root` is a runtime input (where the SDK lives on disk), not derived
/// per-silicon knowledge, so it's threaded in rather than guessed.
fn build_yocto_slice(
    board: &BoardYaml,
    som: &SomPreset,
    core_id: &str,
    build_root: &str,
    sdk_root: &str,
) -> Option<BuildSlice> {
    let slice = resolve_yocto_slice(board, som, core_id)?;
    let build_dir = format!("{build_root}/{core_id}-yocto");
    Some(BuildSlice {
        core_id: core_id.to_string(),
        backend: Backend::Yocto,
        build_dir: build_dir.clone(),
        config_artefacts: vec![GeneratedFile {
            path: format!("{build_dir}/local.conf"),
            contents: render_yocto_local_conf(&slice),
        }],
        command: Some(ToolStep {
            tool: "bitbake".to_string(),
            args: vec![slice.image.clone()],
            cwd: build_dir,
        }),
        env: BTreeMap::from([("ALP_SDK_ROOT".to_string(), sdk_root.to_string())]),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const BOARD_YAML: &str = include_str!("spike_fixtures/oracle/rpmsg-aen.board.yaml");
    const SOM_PRESET: &str = include_str!("spike_fixtures/E1M-AEN701.yaml");
    const ORACLE_BUILD_PLAN: &str = include_str!("spike_fixtures/oracle/rpmsg-aen.build-plan");

    /// Pull `slices[coreId].configArtefacts[0].contents` from the captured emit.
    fn oracle_artefact(core_id: &str) -> String {
        let plan: serde_json::Value = serde_json::from_str(ORACLE_BUILD_PLAN).unwrap();
        plan["slices"]
            .as_array()
            .unwrap()
            .iter()
            .find(|s| s["coreId"] == core_id)
            .unwrap_or_else(|| panic!("oracle has no slice {core_id}"))["configArtefacts"][0]
            ["contents"]
            .as_str()
            .unwrap()
            .to_string()
    }

    #[test]
    fn metadata_deserialises() {
        let board: BoardYaml = serde_yaml::from_str(BOARD_YAML).unwrap();
        assert_eq!(board.som.sku, "E1M-AEN701");
        assert_eq!(board.cores["a32_cluster"].image.as_deref(), Some("alp-image-edge"));
        let som: SomPreset = serde_yaml::from_str(SOM_PRESET).unwrap();
        assert_eq!(som.topology["a32_cluster"].machine.as_deref(), Some("e1m-aen701-a32"));
    }

    /// STAGE A — the headline parity proof: the engine reproduces the SDK's
    /// `a32_cluster` local.conf byte-for-byte, from board.yaml + topology DATA.
    #[test]
    fn a32_cluster_local_conf_matches_sdk_emit_byte_for_byte() {
        let board: BoardYaml = serde_yaml::from_str(BOARD_YAML).unwrap();
        let som: SomPreset = serde_yaml::from_str(SOM_PRESET).unwrap();

        let slice = resolve_yocto_slice(&board, &som, "a32_cluster")
            .expect("a32_cluster resolves as a Yocto slice");
        let ours = render_yocto_local_conf(&slice);

        assert_eq!(
            ours,
            oracle_artefact("a32_cluster"),
            "engine output must equal the SDK emit byte-for-byte"
        );
    }

    /// STAGE B — the *full* a32_cluster build-plan slice (coreId / backend /
    /// buildDir / configArtefacts / command / env) equals the SDK emit. The only
    /// environment-specific field (env.ALP_SDK_ROOT, an absolute path) is a
    /// runtime input, so the oracle's value is threaded in; every *derived* field
    /// then matches exactly.
    #[test]
    fn a32_cluster_full_slice_matches_sdk_emit() {
        let board: BoardYaml = serde_yaml::from_str(BOARD_YAML).unwrap();
        let som: SomPreset = serde_yaml::from_str(SOM_PRESET).unwrap();

        let plan: serde_json::Value = serde_json::from_str(ORACLE_BUILD_PLAN).unwrap();
        let oracle_slice = plan["slices"]
            .as_array()
            .unwrap()
            .iter()
            .find(|s| s["coreId"] == "a32_cluster")
            .unwrap();
        let sdk_root = oracle_slice["env"]["ALP_SDK_ROOT"].as_str().unwrap();

        let ours = build_yocto_slice(&board, &som, "a32_cluster", "build", sdk_root)
            .expect("a32_cluster builds as a Yocto slice");
        let ours_json = serde_json::to_value(&ours).unwrap();

        assert_eq!(
            &ours_json, oracle_slice,
            "the full a32_cluster slice must equal the SDK emit"
        );
    }

    /// The `lib_<name>` → `lib-<name>` recipe transform (the POLICY rule).
    #[test]
    fn library_recipe_transform() {
        assert_eq!(lib_to_recipe("mbedtls"), "lib-mbedtls");
        assert_eq!(lib_to_recipe("nlohmann_json"), "lib-nlohmann-json");
    }
}
