// SPDX-License-Identifier: Apache-2.0
// Project scaffold helpers — catalog data and file generators.
// Extracted here so they can be unit-tested without the VS Code API.

import type { E1mModule, ProjectTemplate } from "./messages";

// ---------------------------------------------------------------------------
// Static catalog (mirrors alp-sdk-upstream/metadata/e1m_modules/*.yaml)
// ---------------------------------------------------------------------------

export const E1M_MODULES: E1mModule[] = [
  { id: "E1M-AEN701", displayName: "E1M-AEN701 (Alif Ensemble E7)", family: "alif-ensemble" },
  { id: "E1M-AEN301", displayName: "E1M-AEN301 (Alif Ensemble E3)", family: "alif-ensemble" },
  { id: "E1M-AEN401", displayName: "E1M-AEN401 (Alif Ensemble E4)", family: "alif-ensemble" },
  { id: "E1M-AEN501", displayName: "E1M-AEN501 (Alif Ensemble E5)", family: "alif-ensemble" },
  { id: "E1M-AEN601", displayName: "E1M-AEN601 (Alif Ensemble E6)", family: "alif-ensemble" },
  { id: "E1M-AEN801", displayName: "E1M-AEN801 (Alif Ensemble E8)", family: "alif-ensemble" },
  { id: "E1M-V2N101", displayName: "E1M-V2N101 (Renesas RZ/V2N)", family: "renesas-rzv2n" },
  { id: "E1M-V2N102", displayName: "E1M-V2N102 (Renesas RZ/V2N, larger memory)", family: "renesas-rzv2n" },
  { id: "E1M-V2M101", displayName: "E1M-V2M101 (Renesas RZ/V2N + DEEPX DX-M1)", family: "renesas-rzv2n" },
  { id: "E1M-V2M102", displayName: "E1M-V2M102 (Renesas RZ/V2N + DEEPX DX-M1, larger memory)", family: "renesas-rzv2n" },
  { id: "E1M-NX9101", displayName: "E1M-NX9101 (NXP i.MX 93)", family: "nxp-imx9" },
];

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: "blank-app",
    title: "Blank Application",
    description: "Minimal starter with CMakeLists.txt, prj.conf, board.yaml, and an empty main.c",
    category: "starter",
    icon: "📄",
  },
  {
    id: "gpio-button-led",
    title: "GPIO Peripheral",
    description: "Button input and LED output using board.yaml pin allocation and the peripheral block helper",
    category: "example",
    icon: "🔘",
    sourceDir: "gpio-button-led",
  },
  {
    id: "lvgl-widgets",
    title: "LVGL UI Application",
    description: "Touchscreen UI with LVGL widgets, animations, and theme support",
    category: "example",
    icon: "🖥️",
    sourceDir: "lvgl-widgets-demo",
  },
  {
    id: "iot-dashboard",
    title: "IoT Dashboard",
    description: "Connected device with sensor data aggregation and cloud reporting",
    category: "example",
    icon: "🌐",
    sourceDir: "iot-dashboard",
  },
  {
    id: "ai-object-detection",
    title: "AI Object Detection",
    description: "Real-time object detection pipeline using the DRP-AI3 or Ethos-U55 accelerator",
    category: "example",
    icon: "🤖",
    sourceDir: "ai-object-detection-realtime",
  },
  {
    id: "audio-loopback",
    title: "Audio Processing",
    description: "I2S audio capture and playback with PDM microphone support",
    category: "example",
    icon: "🎵",
    sourceDir: "audio-loopback",
  },
];

// ---------------------------------------------------------------------------
// File generators
// ---------------------------------------------------------------------------

export function generateBoardYaml(moduleId: string, projectName: string): string {
  return `# board.yaml — ALP SDK project configuration (schema v2)
# Generated by ALP IDE for project: ${projectName}
#
# Edit this file to configure hardware peripherals, build targets,
# and project-level settings.  See docs/board-config.md for the schema.

schema_version: 2

som:
  sku: ${moduleId}

project:
  name: ${projectName}
  version: "0.1.0"
`;
}

export function generateCMakeLists(projectName: string): string {
  return `cmake_minimum_required(VERSION 3.20)

# ALP SDK project — generated by ALP IDE.
# alp_project.py reads board.yaml and generates all build configuration.
# Do not add CONFIG_* here; put Kconfig knobs in prj.conf.

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(${projectName})

target_sources(app PRIVATE src/main.c)
`;
}

export function generateMainC(templateId: string): string {
  if (templateId === "blank-app") {
    return `#include <zephyr/kernel.h>

int main(void)
{
\tprintk("Hello from ${templateId}\\n");
\treturn 0;
}
`;
  }
  return `#include <zephyr/kernel.h>

/* TODO: Copy the full implementation from alp-sdk-upstream/examples/${templateId}/ */

int main(void)
{
\tprintk("${templateId} stub — replace with example implementation\\n");
\treturn 0;
}
`;
}
