// SPDX-License-Identifier: Apache-2.0
//
// A board.yaml this extension writes must mean the same thing to the program
// that READS it.
//
// `serializeBoardConfig`'s in-place arm is the `yaml` package, which follows
// YAML 1.2 — there, `off` is the three-letter string "off" and needs no quotes.
// Every consumer of board.yaml is Python: `tan validate` shells out to
// `scripts/validate_board_yaml.py`, and PyYAML follows YAML 1.1, where a bare
// `off` is the BOOLEAN false. So the one value the wizard writes for a core the
// customer switched off crosses a version boundary and changes type on the way.
//
// Measured on the pinned tan 0.6.0-rc1 against a project `tan init` had just
// created and validated clean (`ok: true`, exit 0). After the wizard's second
// pass wrote `os: off` for one core:
//
//   ok: false  exit: 2
//   validate.schema-violation | ALP-B004: False is not of type 'string'
//   validate.schema-violation | ALP-B003: False is not one of ['zephyr', 'yocto', 'baremetal', 'off']
//
// Quoting that one scalar and changing nothing else returned the file to
// `ok: true`, exit 0. So this is the whole defect, and it is not cosmetic: the
// wizard hands a customer who picked "Off (skip core)" a project the SDK
// refuses.
//
// The SDK's own convention agrees and is unambiguous — every `os: off` in
// `alp-sdk-upstream/examples/**/board.yaml` is written `os: "off"`, as is every
// one in this repo's own `test/fixtures/board.fixtures.js`. The serializer's
// OTHER arm already gets it right: `freshDump` (js-yaml) emits `os: 'off'`.
// Only the in-place arm disagrees with both.
//
// The oracle here is `YAML.parse(text, { version: "1.1" })` — the same document
// read under the same version PyYAML uses.

const test = require("node:test");
const assert = require("node:assert/strict");
const path = require("node:path");

const CORE = path.join(__dirname, "..", "packages", "alp-core");
// `yaml` is alp-core's dependency, not the root's, and pnpm's store is strict.
const YAML = require(require.resolve("yaml", { paths: [CORE] }));

const {
  serializeBoardConfig,
} = require("../packages/alp-core/dist/board/serialize.js");
const {
  applyCoreAssignments,
} = require("../packages/alp-core/dist/project/coreScaffold.js");
const {
  parseBoardConfig,
} = require("../packages/alp-core/dist/board/parse.js");

/** A board.yaml exactly as `tan init` writes one, comments and all. Verbatim
 *  from `tan init --template minimal-app --som E1M-AEN801 --cores
 *  a32_cluster:yocto` on the pinned 0.6.0-rc1. */
const TAN_OUTPUT = `# Generated by \`tan init\`.
# board.yaml describes hardware: the SoM SKU + per-core app map.
# Validate it with \`tan validate\` once an SDK is resolved.

som:
  sku: E1M-AEN801
cores:
  m55_hp:
    os: zephyr
    app: .
  a32_cluster:
    os: yocto
    image: alp-image-edge
`;

/** Read a document the way the SDK's Python validator reads it. */
function readAsPython(text) {
  return YAML.parse(text, { version: "1.1" });
}

test("the 1.1 oracle actually detects an unquoted off — anti-vacuity", () => {
  // Without this, a broken oracle would pass every assertion below and the
  // gate would report green on the exact document that fails `tan validate`.
  const bare = readAsPython("cores:\n  a32_cluster:\n    os: off\n");
  assert.equal(
    bare.cores.a32_cluster.os,
    false,
    "a bare `off` must read as boolean false under YAML 1.1, or this gate " +
      "proves nothing",
  );
  const quoted = readAsPython('cores:\n  a32_cluster:\n    os: "off"\n');
  assert.equal(quoted.cores.a32_cluster.os, "off");
});

test("an off core survives the in-place serializer as the STRING off", () => {
  const board = parseBoardConfig(TAN_OUTPUT);
  const next = applyCoreAssignments(board, [
    { id: "m55_hp", os: "zephyr", app: "./src" },
    { id: "a32_cluster", os: "off", app: "" },
  ]);
  const text = serializeBoardConfig(next, TAN_OUTPUT);

  assert.equal(
    readAsPython(text).cores.a32_cluster.os,
    "off",
    "written unquoted, `os: off` reaches validate_board_yaml.py as boolean " +
      "False and the project is refused with ALP-B003 + ALP-B004",
  );
});

test("an off core survives the fresh-dump serializer as the STRING off", () => {
  // The arm that is already correct. Pinned so a future unification of the two
  // arms cannot regress toward the broken one.
  const next = applyCoreAssignments(parseBoardConfig(TAN_OUTPUT), [
    { id: "a32_cluster", os: "off", app: "" },
  ]);
  const text = serializeBoardConfig(next);

  assert.equal(readAsPython(text).cores.a32_cluster.os, "off");
});

test("both serializer arms agree with a YAML 1.2 reader too", () => {
  // The document must mean ONE thing, not "off under 1.2 and false under 1.1".
  // Quoting satisfies both readers; this is what stops a fix that merely
  // swaps which version is wrong.
  const next = applyCoreAssignments(parseBoardConfig(TAN_OUTPUT), [
    { id: "a32_cluster", os: "off", app: "" },
  ]);
  for (const text of [
    serializeBoardConfig(next, TAN_OUTPUT),
    serializeBoardConfig(next),
  ]) {
    assert.equal(YAML.parse(text).cores.a32_cluster.os, "off");
    assert.equal(readAsPython(text).cores.a32_cluster.os, "off");
  }
});

test("the rule is not special-cased to `off`", () => {
  // `off` is the only YAML 1.1 keyword in the os vocabulary today, so a fix
  // could hard-code that one string and pass every assertion above. board.yaml
  // carries free-form strings elsewhere (`image:`, `app:`, chip ids), and the
  // next 1.1 keyword to land in one of them would be the same defect with a
  // different name. The serializer owes the general rule.
  const KEYWORDS_1_1 = ["off", "on", "yes", "no", "y", "n"];
  for (const word of KEYWORDS_1_1) {
    const board = parseBoardConfig(TAN_OUTPUT);
    const withImage = {
      ...board,
      cores: {
        ...board.cores,
        a32_cluster: { ...board.cores.a32_cluster, image: word },
      },
    };
    const text = serializeBoardConfig(withImage, TAN_OUTPUT);
    assert.equal(
      readAsPython(text).cores.a32_cluster.image,
      word,
      `\`image: ${word}\` must stay the string "${word}" under YAML 1.1`,
    );
  }
});
