const test = require("node:test");
const assert = require("node:assert/strict");

const {
  createBoardYaml,
  createDefaultBoardModel,
  normalizeBoardModel,
  parseBoardModel,
} = require("../packages/alp-core/dist/configurator/service.js");

test("normalizeBoardModel drops empty optional blocks", () => {
  const normalized = normalizeBoardModel({
    schema_version: 1,
    som: { sku: "E1M-AEN701" },
    carrier: { name: "E1M-EVK", populated: {} },
    os: "zephyr",
    libraries: [],
    iot: { wifi: false, mqtt: false, ble: false, tls: false },
    inference: {},
  });

  assert.equal(normalized.libraries, undefined);
  assert.equal(normalized.iot, undefined);
  assert.equal(normalized.inference, undefined);
  assert.deepEqual(normalized.carrier, { name: "E1M-EVK" });
});

test("createBoardYaml serializes the normalized model", () => {
  const yamlText = createBoardYaml(createDefaultBoardModel());

  assert.match(yamlText, /Generated by the ALP SDK VS Code configurator/);
  assert.match(yamlText, /schema_version: 1/);
  assert.match(yamlText, /sku: E1M-AEN701/);
});

test("parseBoardModel returns defaults for invalid scalar yaml", () => {
  const parsed = parseBoardModel("hello");

  assert.deepEqual(parsed, createDefaultBoardModel());
});

test("normalizeBoardModel preserves unknown hand-edited fields", () => {
  const normalized = normalizeBoardModel({
    schema_version: 1,
    som: { sku: "E1M-AEN701" },
    carrier: { name: "E1M-EVK" },
    os: "zephyr",
    custom_flag: true,
    nested_custom: { alpha: 1, beta: "manual" },
  });

  assert.equal(normalized.custom_flag, true);
  assert.deepEqual(normalized.nested_custom, { alpha: 1, beta: "manual" });
});
