# SPDX-License-Identifier: Apache-2.0
# Minimal config: the connectivity pipeline is a stub, so networking/MQTT/mbedTLS
# are left out until the feature is implemented (they only pulled the build down).
CONFIG_ASSERT=y
CONFIG_NEWLIB_LIBC=y
CONFIG_STDOUT_CONSOLE=y
