// SPDX-License-Identifier: Apache-2.0

import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import * as yaml from "js-yaml";
import { boardYamlPath, findSdkRoot, log } from "./util";

/**
 * The configurator panel hosts a webview UI that mirrors the board.yaml
 * schema as dropdowns / checkboxes.  Reads board.yaml on open, posts the
 * parsed model to the webview, accepts a "save" message back that
 * serialises the model and writes board.yaml on disk.  The YAML editor
 * remains available in parallel -- the webview is an additive surface,
 * not a replacement.
 */

interface BoardModel {
    schema_version: number;
    som: { sku: string };
    carrier?: { name: string; populated?: Record<string, boolean> };
    os: string;
    inference?: { backend?: string; default_arena_kib?: number };
    libraries?: string[];
    iot?: { wifi?: boolean; mqtt?: boolean; ble?: boolean; tls?: boolean };
    diagnostics?: { last_error?: boolean; log_level?: string };
}

interface PresetCatalogue {
    skus: string[];
    carriers: { name: string; populated: Record<string, boolean> }[];
    libraries: string[];
    inferenceBackends: string[];
    logLevels: string[];
    osChoices: string[];
}

function loadCatalogue(): PresetCatalogue {
    const sdk = findSdkRoot();
    const cat: PresetCatalogue = {
        skus: [],
        carriers: [],
        libraries: ["etl", "fmt", "nlohmann_json", "doctest",
                    "lvgl", "mbedtls", "cmsis_dsp", "littlefs"],
        inferenceBackends: ["auto", "cpu", "ethos_u", "drpai", "deepx_dx"],
        logLevels: ["error", "warn", "info", "debug", "trace"],
        osChoices: ["zephyr", "yocto", "baremetal"],
    };
    if (!sdk) return cat;

    // SoM SKUs -- every directory under metadata/e1m_modules/ with a
    // som.yaml file is a released MPN.
    const modulesDir = path.join(sdk, "metadata", "e1m_modules");
    if (fs.existsSync(modulesDir)) {
        for (const name of fs.readdirSync(modulesDir)) {
            if (!name.startsWith("E1M-")) continue;
            const presetPath = path.join(modulesDir, name, "som.yaml");
            if (fs.existsSync(presetPath)) cat.skus.push(name);
        }
        cat.skus.sort();
    }

    // Carriers -- every directory under metadata/carriers/ with a
    // board.yaml file is a released carrier.
    const carriersDir = path.join(sdk, "metadata", "carriers");
    if (fs.existsSync(carriersDir)) {
        for (const name of fs.readdirSync(carriersDir)) {
            const presetPath = path.join(carriersDir, name, "board.yaml");
            if (!fs.existsSync(presetPath)) continue;
            try {
                const doc = yaml.load(fs.readFileSync(presetPath, "utf-8")) as
                    { populated?: Record<string, boolean> } | null;
                cat.carriers.push({
                    name,
                    populated: (doc?.populated as Record<string, boolean>) ?? {},
                });
            } catch (e) {
                log(`configurator: failed to parse ${presetPath}: ${e}`);
            }
        }
        cat.carriers.sort((a, b) => a.name.localeCompare(b.name));
    }
    return cat;
}

function loadModel(boardPath: string): BoardModel {
    if (fs.existsSync(boardPath)) {
        const doc = yaml.load(fs.readFileSync(boardPath, "utf-8"));
        if (doc && typeof doc === "object") return doc as BoardModel;
    }
    return {
        schema_version: 1,
        som: { sku: "E1M-AEN701" },
        carrier: { name: "E1M-EVK" },
        os: "zephyr",
        diagnostics: { log_level: "info" },
    };
}

function saveModel(boardPath: string, model: BoardModel): void {
    // Drop empty blocks so the on-disk file stays minimal.
    const clean = JSON.parse(JSON.stringify(model)) as BoardModel;
    if (clean.libraries && clean.libraries.length === 0) delete clean.libraries;
    if (clean.iot) {
        const iotObj = clean.iot as Record<string, unknown>;
        const anyOn = Object.values(iotObj).some((v) => v === true);
        if (!anyOn) delete clean.iot;
    }
    if (clean.inference) {
        if (!clean.inference.backend
            && clean.inference.default_arena_kib === undefined) {
            delete clean.inference;
        }
    }
    if (clean.carrier && clean.carrier.populated) {
        const pops = clean.carrier.populated;
        if (Object.keys(pops).length === 0) delete clean.carrier.populated;
    }
    const yamlText =
        "# Generated by the ALP SDK VS Code configurator.\n" +
        "# Hand-edits are preserved on reload; reordering may not be.\n\n" +
        yaml.dump(clean, { indent: 2, lineWidth: 100, sortKeys: false });
    fs.mkdirSync(path.dirname(boardPath), { recursive: true });
    fs.writeFileSync(boardPath, yamlText, "utf-8");
}

function panelHtml(webview: vscode.Webview, extensionUri: vscode.Uri): string {
    const nonce = String(Math.random()).slice(2);
    const cssUri = webview.asWebviewUri(
        vscode.Uri.joinPath(extensionUri, "media", "configurator.css"));
    const jsUri = webview.asWebviewUri(
        vscode.Uri.joinPath(extensionUri, "media", "configurator.js"));
    const csp =
        `default-src 'none'; ` +
        `style-src ${webview.cspSource}; ` +
        `script-src 'nonce-${nonce}'; ` +
        `font-src ${webview.cspSource};`;
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="${csp}">
    <link rel="stylesheet" href="${cssUri}">
    <title>ALP Board Configurator</title>
</head>
<body>
    <h1>ALP Board Configurator</h1>
    <p class="subtitle">Pick your SoM, carrier, OS, and feature flags.  The YAML editor stays available; this view edits the same <code>board.yaml</code>.</p>

    <section>
        <h2>SoM</h2>
        <label>SKU
            <select id="som-sku"></select>
        </label>
    </section>

    <section>
        <h2>Carrier</h2>
        <label>Name
            <select id="carrier-name"></select>
        </label>
        <details>
            <summary>Per-chip overrides (carrier <code>populated</code> block)</summary>
            <div id="carrier-populated"></div>
        </details>
    </section>

    <section>
        <h2>OS</h2>
        <label>Target backend
            <select id="os-choice"></select>
        </label>
    </section>

    <section>
        <h2>Inference</h2>
        <label>Backend
            <select id="inference-backend">
                <option value="">(use SoM preset's preferred_backend)</option>
            </select>
        </label>
        <label>Tensor arena (KiB)
            <input type="number" id="inference-arena" min="16" placeholder="128">
        </label>
    </section>

    <section>
        <h2>IoT</h2>
        <label><input type="checkbox" id="iot-wifi"> Wi-Fi station path</label>
        <label><input type="checkbox" id="iot-mqtt"> MQTT client</label>
        <label><input type="checkbox" id="iot-ble"> BLE host stack</label>
        <label><input type="checkbox" id="iot-tls"> TLS (MbedTLS-backed &lt;alp/security.h&gt;)</label>
    </section>

    <section>
        <h2>Libraries</h2>
        <div id="libraries"></div>
    </section>

    <section>
        <h2>Diagnostics</h2>
        <label><input type="checkbox" id="diag-last-error" checked> <code>alp_last_error()</code> thread-local slot</label>
        <label>Log level
            <select id="diag-log-level"></select>
        </label>
    </section>

    <div class="actions">
        <button id="save">Save board.yaml</button>
        <button id="reload">Reload from disk</button>
        <span id="status"></span>
    </div>

    <script nonce="${nonce}" src="${jsUri}"></script>
</body>
</html>`;
}

class ConfiguratorPanel {
    private static current: ConfiguratorPanel | undefined;
    private readonly panel: vscode.WebviewPanel;
    private readonly disposables: vscode.Disposable[] = [];

    static show(context: vscode.ExtensionContext): void {
        if (ConfiguratorPanel.current) {
            ConfiguratorPanel.current.panel.reveal(vscode.ViewColumn.Active);
            ConfiguratorPanel.current.refresh();
            return;
        }
        const panel = vscode.window.createWebviewPanel(
            "alpConfigurator",
            "ALP Board Configurator",
            vscode.ViewColumn.Active,
            {
                enableScripts: true,
                retainContextWhenHidden: true,
                localResourceRoots: [
                    vscode.Uri.joinPath(context.extensionUri, "media"),
                ],
            },
        );
        ConfiguratorPanel.current = new ConfiguratorPanel(panel, context);
    }

    private constructor(
        panel: vscode.WebviewPanel,
        context: vscode.ExtensionContext,
    ) {
        this.panel = panel;
        this.panel.webview.html = panelHtml(panel.webview, context.extensionUri);

        this.panel.webview.onDidReceiveMessage(
            (msg) => this.onMessage(msg),
            null, this.disposables);

        this.panel.onDidDispose(() => this.dispose(), null, this.disposables);
        this.refresh();
    }

    private refresh(): void {
        const boardPath = boardYamlPath();
        if (!boardPath) {
            vscode.window.showErrorMessage(
                "Alp: open a workspace folder before launching the configurator.");
            return;
        }
        const model = loadModel(boardPath);
        const catalogue = loadCatalogue();
        this.panel.webview.postMessage({
            type: "init",
            model,
            catalogue,
            boardPath,
        });
    }

    private onMessage(msg: { type: string; payload?: BoardModel }): void {
        if (msg.type === "save" && msg.payload) {
            const boardPath = boardYamlPath();
            if (!boardPath) return;
            try {
                saveModel(boardPath, msg.payload);
                this.panel.webview.postMessage({
                    type: "saved",
                    boardPath,
                });
                vscode.window.setStatusBarMessage(
                    `Alp: saved ${boardPath}`, 5000);
            } catch (e) {
                vscode.window.showErrorMessage(`Alp: save failed: ${e}`);
            }
        } else if (msg.type === "reload") {
            this.refresh();
        }
    }

    private dispose(): void {
        ConfiguratorPanel.current = undefined;
        this.panel.dispose();
        while (this.disposables.length) this.disposables.pop()?.dispose();
    }
}

export function registerConfiguratorCommand(
    context: vscode.ExtensionContext,
): vscode.Disposable {
    return vscode.commands.registerCommand(
        "alp.openConfigurator",
        () => ConfiguratorPanel.show(context));
}
