// SPDX-License-Identifier: Apache-2.0

import * as yaml from "js-yaml";
import { BoardModel, PresetCatalogue } from "./models";

export function createEmptyPresetCatalogue(): PresetCatalogue {
  return {
    skus: [],
    carriers: [],
    libraries: [
      "etl",
      "fmt",
      "nlohmann_json",
      "doctest",
      "lvgl",
      "mbedtls",
      "cmsis_dsp",
      "littlefs",
    ],
    inferenceBackends: ["auto", "cpu", "ethos_u", "drpai", "deepx_dx"],
    logLevels: ["error", "warn", "info", "debug", "trace"],
    osChoices: ["zephyr", "yocto", "baremetal"],
  };
}

export function createDefaultBoardModel(): BoardModel {
  return {
    schema_version: 1,
    som: { sku: "E1M-AEN701" },
    carrier: { name: "E1M-EVK" },
    os: "zephyr",
    diagnostics: { log_level: "info" },
  };
}

export function parseBoardModel(text: string): BoardModel {
  const parsed = yaml.load(text);
  if (parsed && typeof parsed === "object") {
    return parsed as BoardModel;
  }
  return createDefaultBoardModel();
}

export function createBoardYaml(model: BoardModel): string {
  const normalized = normalizeBoardModel(model);
  return (
    "# Generated by the ALP SDK VS Code configurator.\n" +
    "# Hand-edits are preserved on reload; reordering may not be.\n\n" +
    yaml.dump(normalized, { indent: 2, lineWidth: 100, sortKeys: false })
  );
}

export function normalizeBoardModel(model: BoardModel): BoardModel {
  const normalized = JSON.parse(JSON.stringify(model)) as BoardModel;

  // v1: clean up empty top-level optional blocks
  if (normalized.schema_version < 2) {
    if (normalized.libraries && normalized.libraries.length === 0) {
      delete normalized.libraries;
    }

    if (normalized.iot) {
      const hasEnabledIoTFlag = Object.values(normalized.iot).some(
        (value) => value === true,
      );
      if (!hasEnabledIoTFlag) {
        delete normalized.iot;
      }
    }

    if (
      normalized.inference &&
      !normalized.inference.backend &&
      normalized.inference.default_arena_kib === undefined
    ) {
      delete normalized.inference;
    }

    if (normalized.carrier?.populated) {
      if (Object.keys(normalized.carrier.populated).length === 0) {
        delete normalized.carrier.populated;
      }
    }
  }

  // v2: top-level os: has no meaning — remove it if present
  if (normalized.schema_version >= 2 && normalized.os !== undefined) {
    delete normalized.os;
  }

  return normalized;
}
